# Generated by Django 5.1.7 on 2025-04-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_store', '0006_delete_user_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=100, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=36, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(max_length=40, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(max_length=128, null=True, verbose_name='Signature ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDING', max_length=254, verbose_name='Payment Status'),
        ),
    ]
